# Create the basic Kafka Stack to act as the test data pipeline delivery
# 2023-07-16

version: "3.9"

services:

  zookeeper:
    image: "bitnami/zookeeper:3.8.0"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - stream
  
  kafka:
    image: "bitnami/kafka:3.3.1"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,PLAINTEXT_HOST://kafka:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    #volumes:
    #  - /tmp:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - stream

  kafka-ui:
    image: "provectuslabs/kafka-ui:5f4bb43afd3a516176db481944fb5adb3178a40e"
    ports:
      - "9080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=streaming-demo
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kakfa
    networks:
      - stream

networks:
  stream:
